class CommonConstants {
    public readonly DB_KEY_HostInfo_KEY_NAME_Address = 'Address';
    public readonly DB_KEY_HostInfo_KEY_NAME_Password = 'Password';

    public readonly Vibrate_Effect_ID_SOFT = 'haptic.effect.soft';
    public readonly Vibrate_Effect_ID_HARD = 'haptic.effect.hard';

    public readonly AppStorage_KEY_ShortcutPath = 'path';
    public readonly AppStorage_KEY_FormID = 'formID';

    public readonly FormMessage_Update = 'update';
    public readonly FormCall_Run = 'run';
}

export default new CommonConstants();