class StyleConstants {
    public readonly FULL_PERCENT = '100%';
    public readonly NINETY_PERCENT = '90%';
    public readonly EIGHTY_PERCENT = '80%';
    public readonly SEVENTY_FIVE_PERCENT = '75%';
    public readonly SEVENTY_PERCENT = '70%';
    public readonly SIXTY_PERCENT = '60%';
    public readonly FIFTY_PERCENT = '50%';
    public readonly FORTY_PERCENT = '40%';
    public readonly THIRTY_PERCENT = '30%';
    public readonly TWENTY_FIVE_PERCENT = '25%';
    public readonly TWENTY_PERCENT = '20%';
    public readonly FIFTEEN_PERCENT = '15%';
    public readonly THIRTEEN_PERCENT = '13%';
    public readonly TEN_PERCENT = '10%';
    public readonly FIVE_PERCENT = '5%';
    public readonly FOUR_PERCENT = '4%';
    public readonly THREE_PERCENT = '3%';
    public readonly TWO_PERCENT = '2%';
    public readonly ONE_PERCENT = '1%';

    public readonly MARGIN_FIFTY = 50;
    public readonly MARGIN_FORTY = 40;
    public readonly MARGIN_THIRTY = 30;
    public readonly MARGIN_TWENTY = 20;
    public readonly MARGIN_TEN = 10;
    public readonly MARGIN_FIVE = 5;

    public readonly PADDING_TWENTY = 20;
    public readonly PADDING_SIXTEEN = 16;
    public readonly PADDING_FIFTEEN = 15;
    public readonly PADDING_TEN = 10;
    public readonly PADDING_EIGHT = 8;
    public readonly PADDING_FIVE = 5;
    public readonly PADDING_TWO = 2;

    public readonly DIALOG_TITLE_FONT_SIZE = 23;
    public readonly DIALOG_CONTENT_FONT_SIZE = 18;

    public readonly INPUT_BORDER_WIDTH = 1;
    public readonly INPUT_BORDER_RADIUS = 8;

    public readonly LOADING_WIDTH = 128;

    public readonly PROGRESS_STROKE_WIDTH = 18;
    public readonly PROGRESS_WIDTH = 72;
    public readonly PROGRESS_TEXT_FONT_SIZE = 17;
    public readonly BLUE_LEVEL = 10;

    public readonly COMMAND_TILE_COL_SPACE = 12;
    public readonly COMMAND_TILE_ROW_SPACE = 8;
    public readonly COMMAND_TILE_NAME_FONT_SIZE = 16;
    public readonly COMMAND_TILE_COMMAND_FONT_SIZE = 13;
    public readonly COMMAND_TILE_LABEL_FONT_SIZE = 11;
    public readonly COMMAND_TILE_PROGRESS_WIDTH = 64;
    public readonly COMMAND_TILE_PROGRESS_STROKE_WIDTH = 13;

    public readonly SETTINGS_PAGE_TITLE_FONT_SIZE = 24;
    public readonly SETTINGS_PAGE_LABEL_FONT_SIZE = 17;

    public readonly INDEX_SWIPE_BUTTON_SIZE = 40;
    public readonly INDEX_TAB_ICON_SIZE = 30;
    public readonly INDEX_TAB_HEIGHT = 40;
    public readonly INDEX_TAB_LABEL_FONT_SIZE = 12;
    public readonly INDEX_SETUP_FONT_SIZE = 20;
    public readonly INDEX_NO_ENTRY_TITLE_FONT_SIZE = 18;
    public readonly INDEX_NO_ENTRY_SECOND_TITLE_FONT_SIZE = 14;
    public readonly INDEX_LAYOUT_WEIGHT = 1;

    public readonly EDIT_PAGE_BLANK_COL_SPACE = 20;
    public readonly EDIT_PAGE_OPTION_COL_SPACE = 15;
    public readonly EDIT_PAGE_ROW_SPACE = 10;
    public readonly EDIT_PAGE_LABEL_FONT_SIZE = 18;
    public readonly EDIT_PAGE_CHECK_LABEL_FONT_SIZE = 16;

    public readonly ADD_COMMAND_COL_SPACE = 20;
    public readonly ADD_COMMAND_OPTION_COL_SPACE = 15;
    public readonly ADD_COMMAND_ROW_SPACE = 10;
    public readonly ADD_COMMAND_LABEL_FONT_SIZE = 18;
    public readonly ADD_COMMAND_CHECK_LABEL_FONT_SIZE = 16;

    public readonly MORE_MENU_ITEM_ICON_SIZE = 28;
    public readonly MORE_MENU_ITEM_FONT_SIZE = 17;
    public readonly MORE_MENU_VERSION_FONT_SIZE = 13;

    public readonly LIVE_TEST_LABEL_FONT_SIZE = 17;
    public readonly LIVE_TEST_INPUT_BORDER_WIDTH = 1;

    public readonly FORM_RESULT_CONTENT_FONT_SIZE = 15;
    public readonly FORM_RESULT_LABEL_FONT_SIZE = 10;
    public readonly FORM_RUNNING_LABEL_FONT_SIZE = 13;
}

export default new StyleConstants();