class StyleConstants {
    public FULL_PERCENT = '100%';
    public EIGHTY_PERCENT = '80%';
    public SEVENTY_FIVE_PERCENT = '75%';
    public SEVENTY_PERCENT = '70%';
    public SIXTY_PERCENT = '60%';
    public FIFTY_PERCENT = '50%';
    public FORTY_PERCENT = '40%';
    public THIRTY_PERCENT = '30%';
    public TWENTY_FIVE_PERCENT = '25%';
    public TWENTY_PERCENT = '20%';
    public FIFTEEN_PERCENT = '15%';
    public TEN_PERCENT = '10%';
    public FIVE_PERCENT = '5%';
    public FOUR_PERCENT = '4%';
    public THREE_PERCENT = '3%';
    public TWO_PERCENT = '2%';
    public ONE_PERCENT = '1%';

    public MARGIN_TWENTY = 20;
    public MARGIN_TEN = 10;

    public PADDING_TWENTY = 20;
    public PADDING_SIXTEEN = 16;
    public PADDING_EIGHT = 8;
    public PADDING_FIVE = 5;
    public PADDING_TWO = 2;

    public DIALOG_TITLE_FONT_SIZE = 23;
    public DIALOG_CONTENT_FONT_SIZE = 18;

    public COMMAND_TILE_COL_SPACE = 12;
    public COMMAND_TILE_ROW_SPACE = 8;
    public COMMAND_TILE_NAME_FONT_SIZE = 16;
    public COMMAND_TILE_COMMAND_FONT_SIZE = 13;
    public COMMAND_TILE_LABEL_FONT_SIZE = 11;
}

export default new StyleConstants();