import { deviceInfo, BusinessError, systemDateTime } from '@kit.BasicServicesKit';
import { promptAction } from '@kit.ArkUI';
import { PromptAction } from '@ohos.arkui.UIContext';
import { picker, fileIo as fs } from '@kit.CoreFileKit';
import { common } from '@kit.AbilityKit';
import { buffer } from '@kit.ArkTS';
import { vibrator } from '@kit.SensorServiceKit';

import Logger from './Logger';
import { ExportJson } from '../../model/JsonObjects';

class CommonUtils {
    private LOG_TAG = "[CommonUtils]";

    // 按照 API 版本显示 Toast 提醒
    public alert(message: string | Resource, newerPromptAction: PromptAction) {
        if(deviceInfo.sdkApiVersion <= 17) {
            try {
                promptAction.showToast({
                    message: message
                });
            } catch (err) {
                Logger.error(this.LOG_TAG, `<alert API <= 17> 错误, ${err}`);
            }
        } else {
            newerPromptAction.openToast({
                message: message
            }).catch((err: BusinessError) => {
                Logger.error(this.LOG_TAG, `<alert API > 17> 错误, ${err}`);
            });
        }
    }

    // 从 NavDestination 由 pop() 返回时
    // 显示回调 popInfo
    public returnFromSubPage(popInfo: PopInfo): void {
        Logger.debug(this.LOG_TAG,
            `从 [${popInfo.info.name}] 页面返回, 携带参数: ${JSON.stringify(popInfo.result)}`);
    }

    public vibrate() {
        try {
            vibrator.isSupportEffect('haptic.effect.hard', (err: BusinessError, state: boolean) => {
                if (err) {
                    Logger.error(this.LOG_TAG, `查询振动效果失败, 代码: ${err.code}, 错误信息: ${err.message}`);
                    return;
                }

                Logger.info(this.LOG_TAG, 'Succeed in querying effect');

                if (state) {
                    try {
                        // 触发马达振动
                        vibrator.startVibration({
                            type: 'preset',
                            effectId: 'haptic.effect.hard',
                            count: 1,
                            intensity: 100,
                        }, {
                            usage: 'unknown'
                        }, (error: BusinessError) => {
                            if (error) Logger.error(this.LOG_TAG, `振动触发失败, 代码: ${error.code}, 错误信息: ${error.message}`);
                            else Logger.info(this.LOG_TAG, '成功触发振动');
                        });
                    } catch (error) {
                        Logger.error(this.LOG_TAG, `振动发生未知错误, ${error}`);
                    }
                }
            });
        } catch (error) {
            Logger.error(this.LOG_TAG, `振动发生未知错误, ${error}`);
        }
    }

    // 获取时间（毫秒）
    public getDate(): string {
        let date = new Date(systemDateTime.getTime());

        const formattedTime = `${date.getTime().toString()}`;
        Logger.debug(this.LOG_TAG, formattedTime);

        return formattedTime;
    }

    // 导出功能
    // 保存到文件
    public async saveToFile(json: string, context: common.UIAbilityContext): Promise<boolean> {
        let jsonFilename = `ASFShortcut-backup-${this.getDate()}.json`;

        const documentSaveOptions = new picker.DocumentSaveOptions();
        documentSaveOptions.newFileNames = [jsonFilename];
        documentSaveOptions.fileSuffixChoices = [".json"];

        const documentViewPicker = new picker.DocumentViewPicker(context);

        try {
            const uris = await documentViewPicker.save(documentSaveOptions);
            Logger.debug(this.LOG_TAG, `已选取保存路径: ${uris}`);

            if (uris.length > 0) {
                let savePath: string = uris[0];

                let jsonFile = fs.openSync(savePath, fs.OpenMode.READ_WRITE | fs.OpenMode.CREATE);

                let writeLen = fs.writeSync(jsonFile.fd, json);
                Logger.debug(this.LOG_TAG, `配置文件已保存, 路径: ${jsonFile.path}, 写入长度: ${writeLen}`);

                fs.closeSync(jsonFile);
                return true;
            }

            Logger.warn(this.LOG_TAG, "没有选取保存路径");
            return false;
        } catch (err) {
            Logger.error(this.LOG_TAG, `保存失败, 代码: ${err.code},  ${err.message}`);
            throw new Error("备份导出失败");
        }
    }

    // 导入功能
    // 选择备份文件路径
    public async pickFile(context: common.UIAbilityContext): Promise<string[]> {
        const documentSelectOptions = new picker.DocumentSelectOptions();
        documentSelectOptions.maxSelectNumber = 1;
        documentSelectOptions.fileSuffixFilters = [".json"];

        const documentViewPicker = new picker.DocumentViewPicker(context);
        const uris = await documentViewPicker.select(documentSelectOptions);

        Logger.debug(this.LOG_TAG, `选取文件: ${uris}`);
        return uris;
    }

    // 导入功能
    // 读取备份文件
    public async readFile(uri: string): Promise<string | undefined> {
        try {
            let file = fs.openSync(uri, fs.OpenMode.READ_ONLY);

            let fileStat = fs.statSync(file.fd);
            let fileSize = fileStat.size;
            Logger.debug(this.LOG_TAG, `文件大小: ${fileSize} 字节`);

            // 读取文件
            // cannot use readText(Sync), throws 13900002 error(No such file or directory)
            let arrayBuffer = new ArrayBuffer(fileSize);
            let readLen = fs.readSync(file.fd, arrayBuffer);

            Logger.debug(this.LOG_TAG, `从文件读取 ${readLen} 字节`);
            if (readLen !== fileSize) Logger.warn(this.LOG_TAG,
                `应读取 ${fileSize} 字节, 但实际读取 ${readLen}`);

            let jsonString = buffer.from(arrayBuffer, 0, readLen).toString();

            fs.closeSync(file);

            Logger.debug(this.LOG_TAG, `读取成功, 内容长度: ${jsonString.length}`);
            return jsonString;
        } catch (err) {
            Logger.error(this.LOG_TAG, `文件读取失败, ${err}`);
            return undefined;
        }
    }

    // 导入功能
    // 解析 json 字符串到 ExportJson 对象
    public async parseData(jsonStr: string): Promise<ExportJson> {
        try {
            const exportJson = JSON.parse(jsonStr) as ExportJson;

            if (Array.isArray(exportJson.CommandEntryList)) {
                Logger.debug(this.LOG_TAG, `数据解析成功, 指令列表长度: ${exportJson.CommandEntryList.length}`);
                return exportJson;
            } else throw new Error("解析失败，指令列表非数组");
        } catch (err) {
            Logger.error(this.LOG_TAG, `数据解析失败, 代码: ${err.code}, 错误信息: ${err.message}`);
            throw new Error(err);
        }
    }
}

export default new CommonUtils();